const coaches=[["Greg Plank","Head Swim Coach"],["Joe Underwood","Assistant Swim Coach"],["Joe Cyr","Head Dive Coach"]];
const steps=["Register in Aktivate","Complete & upload physical","Verify athletic clearance","Complete team registration","Pay team/booster fees","Ready for the pool"];
export default function Home(){return <main>
<section className="hero"><div className="heroInner"><p className="eyebrow">HOME OF THE THUNDER · 2026 SEASON</p><h1>DESERT VISTA<br/><em>SWIM & DIVE</em></h1><p className="lead">Built for swimmers, divers, families and fans. Everything for the season in one place.</p><div className="actions"><a className="primary" href="#register">2026 Registration</a><a className="secondary" href="#schedule">View Schedule</a></div></div><div className="wave">DV</div></section>
<section className="ticker"><b>2026 SEASON</b><span>Follow team updates, photos & highlights on Instagram</span><a href="https://www.instagram.com/dvthunderswimdive/">@dvthunderswimdive →</a></section>
<section className="section" id="schedule"><div className="sectionHead"><div><p className="eyebrow dark">MEET CENTRAL</p><h2>Next meet</h2></div><span className="status">Schedule updating</span></div><div className="meet"><div><small>2026 SEASON</small><h3>Thunder Swim & Dive</h3><p>The current meet schedule and results will live here as dates are confirmed.</p></div><div className="meetLinks"><a href="#schedule">Meet schedule</a><a href="#volunteer">Volunteer</a></div></div></section>
<section className="champ"><div><span>2025</span><h2>GIRLS STATE<br/>CHAMPIONS</h2><p>Celebrating a championship season and the athletes who made Desert Vista history.</p></div><div className="trophy">🏆</div></section>
<section className="section" id="team"><p className="eyebrow dark">THE TEAM</p><h2>Thunder coaches</h2><div className="cards">{coaches.map(([n,r])=><article className="card" key={n}><div className="avatar">{n.split(" ").map(x=>x[0]).join("")}</div><h3>{n}</h3><p>{r}</p></article>)}</div></section>
<section className="section alt" id="register"><p className="eyebrow dark">GET READY</p><h2>2026 registration</h2><p className="intro">Athletes must be fully cleared before participating. Use this checklist to keep the process simple.</p><div className="steps">{steps.map((s,i)=><div className="step" key={s}><b>{i+1}</b><span>{s}</span></div>)}</div></section>
<section className="section" id="records"><div className="sectionHead"><div><p className="eyebrow dark">THUNDER HISTORY</p><h2>Record book</h2></div><span className="status gold">Migration in progress</span></div><p className="intro">Girls and boys school records will be organized by event with record-holder, time and year. Historical entries are being preserved and questionable legacy entries will be flagged for verification.</p><div className="recordPreview"><div><small>FREESTYLE</small><strong>50 · 100 · 200 · 500</strong></div><div><small>PLUS</small><strong>Fly · Back · Breast · IM · Diving · Relays</strong></div></div></section>
<section className="section alt" id="parents"><p className="eyebrow dark">PARENTS & ATHLETES</p><h2>Everything in one place</h2><div className="linkGrid"><a href="#register">Athletic clearance <span>→</span></a><a href="#register">Registration & fees <span>→</span></a><a href="#volunteer">Volunteer <span>→</span></a><a href="#records">Team records <span>→</span></a><a href="https://www.instagram.com/dvthunderswimdive/">Instagram <span>→</span></a><a href="#contact">Contact <span>→</span></a></div></section>
<section className="section" id="volunteer"><p className="eyebrow dark">BOOST THE THUNDER</p><h2>Volunteer</h2><p className="intro">Home meets rely on parent volunteers for setup, timing, head timing and running timer sheets. Families can also support the team with food, equipment and photography.</p></section>
<section className="instagram"><div><p className="eyebrow">THUNDER SOCIAL</p><h2>Follow the season</h2><p>Team updates, announcements, photos and highlights from @dvthunderswimdive.</p></div><a className="primary" href="https://www.instagram.com/dvthunderswimdive/">Open Instagram</a></section>
</main>}