const quick=[["2026 Schedule","/schedule"],["Registration & Clearance","/parents#register"],["Thunder Record Book","/records"],["State Championship Results","/results"],["Meet the Coaches","/team"],["Contact","/contact"]];
export default function Home(){return <main>
<section className="hero"><div className="heroInner"><p className="eyebrow">HOME OF THE THUNDER · 2026 SEASON</p><h1>DESERT VISTA<br/><em>SWIM & DIVE</em></h1><p className="lead">The season hub for Thunder swimmers, divers, families and fans.</p><div className="actions"><a className="primary" href="/parents#register">Registration Hub</a><a className="secondary" href="/schedule">2026 Schedule</a></div></div><div className="wave">DV</div></section>
<section className="ticker"><b>2026 SEASON</b><span>Team updates, announcements, photos & highlights</span><a href="https://www.instagram.com/dvthunderswimdive/">@dvthunderswimdive →</a></section>
<section className="section"><p className="eyebrow dark">SEASON CENTRAL</p><h2>Quick links</h2><div className="linkGrid">{quick.map(([n,u])=><a href={u} key={n}>{n}<span>→</span></a>)}</div></section>
<section className="section alt announcementStrip"><div><p className="eyebrow dark">THUNDER NEWS</p><h2>2026 announcements</h2><p className="intro">Registration, gear and season updates are maintained separately from social media so important information is easy to find.</p></div><a className="primary" href="/announcements">View announcements</a></section>
<section className="champ"><div><span>2025</span><h2>GIRLS STATE<br/>CHAMPIONS</h2><p>Celebrating the championship team, two record-setting relays and the athletes who made Desert Vista history.</p><a className="primary" href="/results">State results</a></div><div className="trophy">🏆</div></section>
<section className="section"><div className="sectionHead"><div><p className="eyebrow dark">2026 SEASON</p><h2>Meet central</h2></div><a className="status gold" href="/schedule">Full schedule →</a></div><div className="meet"><div><small>UPCOMING SCHEDULE</small><h3>Thunder Swim & Dive</h3><p>Meet dates, opponents, locations and qualifier events are now organized in one place.</p></div><div className="meetLinks"><a href="/schedule">Schedule</a><a href="/parents">Parent hub</a></div></div></section>
<section className="section alt"><p className="eyebrow dark">THUNDER RECORD BOOK</p><h2>History lives here</h2><p className="intro">Explore Desert Vista's top performances across freestyle, butterfly, backstroke, breaststroke, IM and relays. Legacy data is being cleaned carefully while preserving the source record.</p><div className="actions darkActions"><a className="primary" href="/records">Explore records</a></div></section>
<section className="instagram"><div><p className="eyebrow">THUNDER SOCIAL</p><h2>Follow the season</h2><p>For current announcements, photos and highlights, follow the team's official Instagram account.</p></div><a className="primary" href="https://www.instagram.com/dvthunderswimdive/">Open Instagram</a></section>
</main>}