export const metadata={alternates:{canonical:"/"},openGraph:{url:"/"}};
const quick=[["Calendar","/schedule","▣"],["Meet Schedule","/schedule","◷"],["Register","/parents#register","✓"],["Team Store","/store","◆"],["Volunteer","/boosters","♡"],["Records","/records","★"]];
const next=[["NEXT MEET","Millennium","Sep 3 · 4:00 PM · NOZOMI Park","/schedule","◷"],["NEXT QUALIFIER","Eagle Invite","Sep 25–26 · Phoenix Country Day School","/schedule","▣"],["IMPORTANT","Athlete Registration","Clearance required before participation","/parents#register","!"]];
export default function Home(){return <main className="homeRefresh">
<section className="homeHero"><div className="homeHeroShade"></div><div className="homeHeroContent"><p className="homeKicker">DESERT VISTA HIGH SCHOOL</p><h1>DESERT VISTA<br/>SWIM & DIVE</h1><p className="homeScript">Home of the Thunder</p><div className="homeHeroActions"><a className="homeGoldBtn" href="/parents">2026 Season Info ›</a><a className="homeOutlineBtn" href="/schedule">View Calendar ›</a></div></div></section>
<section className="homeShell nextUp"><div className="homeSectionTitle"><span></span><h2>Next Up</h2><span></span></div><div className="nextGrid">{next.map(([label,title,detail,url,icon])=><article className="nextCard" key={title}><div className="roundIcon">{icon}</div><div><small>{label}</small><h3>{title}</h3><p>{detail}</p><a href={url}>View details ›</a></div></article>)}</div></section>
<section className="homeShell homeFeatureGrid"><article className="homePanel newsPanel"><p className="panelLabel">Thunder News</p><h2>2026 Season</h2><p>Registration, team gear and season updates are organized in one place so families can quickly find what they need.</p><a href="/announcements">Read the latest ›</a></article><article className="homePanel championPanel"><div className="champIcon">🏆</div><div><h2>Girls State Champions!</h2><p>Celebrating the 2025 State Championship team, record-setting relays and the athletes who made Desert Vista history.</p><a href="/results">Read full story ›</a></div></article><article className="homePanel quickPanel"><div className="homeSectionTitle compact"><span></span><h2>Quick Links</h2><span></span></div><div className="quickTiles">{quick.map(([name,url,icon])=><a href={url} key={name}><b>{icon}</b><span>{name}</span></a>)}</div><a className="wideGold" href="/parents">View all parent resources ›</a></article></section>
<section className="homeShell lowerGrid"><article className="homePanel recordPanel"><div className="homeSectionTitle compact"><h2>Thunder Record Book</h2><span></span></div><p className="panelLabel goldText">School Record Highlights</p><div className="recordRows"><p><b>200 Medley Relay</b><span>1:45.25 · 2025</span></p><p><b>200 Free Relay</b><span>1:35.59 · 2025</span></p><p><b>400 Free Relay</b><span>3:28.49 · 2025</span></p></div><a className="panelButton" href="/records">View all records ›</a></article><article className="homePanel thunderPanel"><div className="homeSectionTitle compact"><span></span><h2>Meet the Thunder</h2><span></span></div><div className="thunderCards"><a href="/team"><div className="photoPlaceholder">DV</div><b>Swimmers & Divers</b><small>Meet our athletes</small></a><a href="/team"><div className="photoPlaceholder coach">DV</div><b>Coaches</b><small>Meet the staff</small></a><a href="/team"><div className="photoPlaceholder senior">DV</div><b>Thunder Team</b><small>Meet the team</small></a></div></article></section>
<section className="supportBand"><div className="homeShell supportInner"><div className="supportTitle"><h2>Support DV<br/>Swim & Dive</h2></div><a href="/boosters"><b>♡ Volunteer</b><span>Get involved ›</span></a><a href="/boosters"><b>♙ Booster Club</b><span>Learn more ›</span></a><a href="/boosters"><b>◇ Support</b><span>Help the Thunder ›</span></a><div className="socialBlock"><b>Follow the Thunder</b><a href="https://www.instagram.com/dvthunderswimdive/">@dvthunderswimdive</a></div></div></section>
</main>}